version: "3.7"

networks:
  docker.network:
    driver: bridge

services:
  app:
    build: ./docker/php
    restart: unless-stopped
    container_name: app
    tty: true
    depends_on:
      # - mysql
      - postgres
      # - redis
    networks:
      - docker.network
    volumes:
      - .:/var/www

  # nginx:
  #   build: ./docker/nginx
  #   container_name: nginx
  #   restart: unless-stopped
  #   tty: true
  #   depends_on:
  #     - app
  #   ports:
  #     - "433:433"
  #     - "81:80"
  #   networks:
  #     - docker.network
  #   volumes:
  #     - ./:/var/www
  #     - ./docker/nginx/default.conf/:/etc/nginx/default.conf/

  apache:
    build: ./docker/apache
    restart: unless-stopped
    container_name: apache
    tty: true
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    networks:
      - docker.network
    volumes:
      - .:/var/www

  #  mariadb:
  #    image: mariadb
  #    restart: unless-stopped
  #    container_name: docker.mariadb
  #    tty: true
  #    ports:
  #      - '3306:3306'
  #    networks:
  #      - docker.network
  #    volumes:
  #      - './docker/mysql/mariadb.cnf:/etc/mysql/conf.d/custom.cnf:ro'
  #      - './docker/mysql/dbdata:/var/lib/mysql'
  #    environment:
  #      MYSQL_DATABASE: ${MYSQL_DATABASE:-development}
  #      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
  #      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mysql}
  #      MYSQL_USER: ${MYSQL_USER:-mysql}

  # mysql:
  #   image: mysql:5
  #   restart: unless-stopped
  #   container_name: docker.mysql
  #   tty: true
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - docker.network
  #   volumes:
  #     - "./docker/mysql/mysql.cnf:/etc/mysql/conf.d/custom.cnf:ro"
  #     - "./docker/mysql/dbdata:/var/lib/mysql"
  #   environment:
  #     MYSQL_DATABASE: ${MYSQL_DATABASE:-development}
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mysql}
  #     MYSQL_USER: ${MYSQL_USER:-mysql}

  # phpmyadmin:
  #   image: phpmyadmin
  #   container_name: docker.phpmyadmin
  #   tty: true
  #   depends_on:
  #     - mysql
  #   ports:
  #     - "8080:80"
  #   networks:
  #     - docker.network
  #   environment:
  #     PMA_HOST: mysql
  #     PMA_ARBITRARY: 1
  #     PMA_PORT: 3306

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    networks:
      - docker.network
    volumes:
      - "./docker/postgres/dbdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-development}

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   tty: true
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "8081:80"
  #   networks:
  #     - docker.network
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@localhost.com}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}

  # redis:
  #   image: bitnami/redis:latest
  #   restart: unless-stopped
  #   container_name: docker.redis
  #   tty: true
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - docker.network
  #   volumes:
  #     - ./docker/redis:/bitnami/redis/data
  #   environment:
  #     ALLOW_EMPTY_PASSWORD: ${REDIS_ALLOW_EMPTY_PASSWORD:-no}
  #     REDIS_PASSWORD: ${REDIS_PASSWORD:-redis}